git:
  autoFetch: false # If true, periodically fetch from remote
gui:
  nerdFontsVersion: "3"
  showFileTree: false # for rendering changes files in a tree format
  timeFormat: "2006-01-02 15:04:05" # https://pkg.go.dev/time#Time.Format
os:
  editPreset: "nvim-remote"
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
customCommands:
  - key: <c-a>
    description: "[xndv] Choose AI-generated commit"
    command: x-git-commit
    context: files
    output: terminal
  - key: <c-p>
    description: "[xndv] Preview image with Kitty"
    command: "kitty +kitten icat --hold {{.SelectedFile.Name}}"
    context: files
    output: terminal
