gui:
  nerdFontsVersion: "3"
  showFileTree: false # for rendering changes files in a tree format
  timeFormat: "2006-01-02 15:04:05" # https://pkg.go.dev/time#Time.Format
os:
  editPreset: "nvim-remote"
promptToReturnFromSubprocess: false # display confirmation when subprocess terminates
