# tinty configuration
# https://github.com/tinted-theming/tinty

shell = "sh -c '{}'"

default-scheme = "base24-tokyo-night-dark"
default-cycle-ring = "default"

[[rings]]
name = "default"
schemes = ["base24-gruvbox-dark-hard", "base24-tokyo-night-dark"]

# tinted-shell: Updates terminal colors via OSC escape sequences
[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
supported-systems = ["base24"]
hook = ". %f"

# tinted-tmux: Applies theme to tmux status bar and panes
[[items]]
name = "tinted-tmux"
path = "https://github.com/tinted-theming/tinted-tmux"
themes-dir = "colors"
supported-systems = ["base24"]
hook = "tmux run 2> /dev/null && tmux source-file %f && ~/src/xndv/bin/x-fix-tinted-tmux.sh"

# tinted-kitty: Applies theme to kitty terminal
# https://github.com/tinted-theming/tinted-terminal?tab=readme-ov-file#kitty
[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/kitty"
supported-systems = ["base24"]
hook = "command -v kitten >/dev/null && kitten @ load-config"
