format = """
$all\
"""

right_format = """
$time\
"""

# remove '⬢ [Systemd]'
# https://github.com/starship/starship/issues/4216
[container]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[time]
disabled = false
format = '[  $time ]($style) '
time_format = "%Y-%m-%d %H:%M:%S"
